version: "3.0"

services:
  jupyter:
    container_name: jupyter
    image: jupyter
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
    command: jupyter notebook --allow-root --ip=0.0.0.0 --no-browser 
